name: ci

on:
  push:
    branches: ['main']
  schedule:
    - cron: '55 23 * * 0'
  repository_dispatch:
    types: [build_application]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/hugheylab/stocker:latest

  
  push-socker:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.JAKEJH_PAT }}
    steps:
      - name: Trigger socker Build
        run: |
          curl -XPOST -u "jakejh:${{secrets.JAKEJH_PAT}}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/hugheylab/socker/dispatches --data '{"event_type": "build_application"}'
        shell: bash
